#!/bin/sh
#------------------------------------------------------------------------------
# Allclean - sedExnerFoam case
#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf constant/polyMesh/sets
rm -rf constant/faMesh
rm -rf 0/finite-area
rm -rf 0_org/finite-area
rm -f  log.*

#------------------------------------------------------------------------------
