#!/bin/sh
#------------------------------------------------------------------------------
# Allrun - sedExnerFoam 2D pipeline scour
# Baseline : DKS-MANAGER/2DPipelineScour      (sedFoam Euler-Euler two-phase)
# This case: DKS-MANAGER/2DPipelineScourEXN   (sedExnerFoam moving mesh)
#
# WORKFLOW (Option A - generate fresh mesh):
#   1. blockMesh        - 3-block background mesh (578x80 cells)
#   2. snappyHexMesh    - carve cylinder D=0.05m, gap e/D=0.02
#   3. checkMesh        - verify 7 patches, non-ortho < 70
#   4. makeFaMesh       - finite-area mesh on 'bottom' patch (Exner)
#   5. restore 0_org    - initial conditions
#   6. sedExnerFoam     - run solver to t=45s
#
# WORKFLOW (Option B - use baseline polyMesh directly, RECOMMENDED):
#   cp -r /path/to/2DPipelineScour/constant/polyMesh constant/polyMesh
#   makeFaMesh
#   cp -r 0_org/. 0/
#   sedExnerFoam 2>&1 | tee log.sedExnerFoam
#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication checkMesh
runApplication makeFaMesh

cp -r 0_org/. 0/

runApplication sedExnerFoam

#------------------------------------------------------------------------------
